apiVersion: v2
name: chartmuseum-migrator
description: Migrate Helm charts from SRC to TGT using Vault (no overwrite)
type: application
version: 20251106-183744
appVersion: "20251106-183744"
home: https://github.com/
