image:
  repository: ghcr.io/vladarh/chartmuseum-rnd-migrator
  tag: "20251106-200802"
  pullPolicy: IfNotPresent

env:
  SRC_URL: ""
  SRC_USER: ""
  SRC_PASS: ""
  TGT_URL: ""
  TGT_USER: ""
  TGT_PASS: ""
  VAULT_ADDR: ""
  VAULT_TOKEN: ""
  EXTRA_ARGS: ""
